language: generic

sudo: required

services:
    - docker

before_install:
    - docker build -t pocketpaul/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true pocketpaul/docker-react npm run test